---
- hosts: all
  remote_user: admin
  sudo: yes
  tasks:
      - name: Add User 
        user: name=ansible
              group=admin

      - name: Adding keys to authorized_keys
        authorized_key: user=ansible
                        key="{{lookup('file', item)}}"
                        path=/home/ansible/.ssh/authorized_keys
                        state=present
        with_fileglob:
             - ./pub-keys/ansible.pub
